FROM jenkins/inbound-agent:alpine as base
USER root
WORKDIR /home
COPY ./assets/ .
ADD https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz openshift.tar.gz

RUN mkdir -p oc-cli gradle && \
    tar -xvf openshift.tar.gz -C ./oc-cli --strip-components 1 && \
    chmod +x ./libs/transformxml

FROM jenkins/inbound-agent:alpine
USER root

RUN apk update && \
    apk add --no-cache \
    ca-certificates \
    git \
    docker \
    maven \
    jq

COPY --from=base /home/libs/transformxml /usr/local/bin
COPY --from=base /home/oc-cli/oc /usr/local/bin
COPY --from=base /home/maven_settings.xml /root/.m2/settings.xml
COPY --from=base /home/ca.crt /usr/local/share/ca-certificates/ca.crt
COPY --from=base /home/openshift-node-client-ca.crt /usr/local/share/ca-certificates/openshift-node-client-ca.crt
COPY --from=base /home/certs/aycapsu01ts471.cer aycapsu01ts471.cer
COPY --from=base /home/certs/aycapsu01ts472.cer aycapsu01ts472.cer

RUN update-ca-certificates
RUN  keytool \
    -import \
    -trustcacerts \
    -alias aycapsu01ts472.dso.aycap.bayad.co.th \
    -keystore $JAVA_HOME/jre/lib/security/cacerts \
    -file aycapsu01ts472.cer \
    -storepass changeit \
    -noprompt
RUN keytool \
    -import \
    -trustcacerts \
    -alias aycapsu01ts471.dso.aycap.bayad.co.th \
    -keystore $JAVA_HOME/jre/lib/security/cacerts \
    -file aycapsu01ts471.cer \
    -storepass changeit \
    -noprompt

VOLUME [ "/var/run/docker.sock" ]