FROM jenkins/inbound-agent:alpine as base
USER root
WORKDIR /home
COPY ./assets/ .
ADD https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz openshift.tar.gz
ADD https://github.com/jeremylong/DependencyCheck/releases/download/v6.1.1/dependency-check-6.1.1-release.zip dependency-check-6.1.1-release.zip

RUN mkdir -p oc-cli && \
    tar -xvf openshift.tar.gz -C ./oc-cli --strip-components 1 && \
    chmod +x ./libs/transformxml && \
    unzip dependency-check-6.1.1-release.zip && \
    chmod +x dependency-check/bin/dependency-check.sh

FROM python:3.7-alpine
ENV URL=""
ENV SECRET=""
ENV WORKDIR=""
ENV JAVA_HOME="/usr/lib/jvm/java-1.8-openjdk"
USER root

RUN apk update && \
    apk add --no-cache \
    ca-certificates \
    git \
    docker \
    openjdk8 \
    ansible

COPY --from=base /home/libs/transformxml /usr/local/bin
COPY --from=base /home/oc-cli/oc /usr/local/bin
COPY --from=base /home/maven_settings.xml /root/.m2/settings.xml
COPY --from=base /home/dependency-check /opt/dependency-check
COPY --from=base /home/ca.crt /usr/local/share/ca-certificates/ca.crt
COPY --from=base /home/openshift-node-client-ca.crt /usr/local/share/ca-certificates/openshift-node-client-ca.crt
COPY --from=base /home/agent.jar .
COPY --from=base /home/certs/aycapsu01ts471.cer .
COPY --from=base /home/certs/aycapsu01ts472.cer .

RUN update-ca-certificates&& \
    ln -s /opt/dependency-check/bin/dependency-check.sh /usr/local/bin/dependency-check
RUN  keytool \
    -import \
    -trustcacerts \
    -alias aycapsu01ts472.dso.aycap.bayad.co.th \
    -keystore $JAVA_HOME/jre/lib/security/cacerts \
    -file aycapsu01ts472.cer \
    -storepass changeit \
    -noprompt && \
    keytool \
    -import \
    -trustcacerts \
    -alias aycapsu01ts471.dso.aycap.bayad.co.th \
    -keystore $JAVA_HOME/jre/lib/security/cacerts \
    -file aycapsu01ts471.cer \
    -storepass changeit \
    -noprompt

VOLUME [ "/var/run/docker.sock" ]
CMD java -jar agent.jar -jnlpUrl ${URL} -secret ${SECRET} -workDir "${WORKDIR}"