FROM jenkins/inbound-agent:alpine as base
ENV MAVEN_VERSION 3.6.3
USER root
WORKDIR /home
COPY ./assets/ .
ADD https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz openshift.tar.gz
ADD http://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz maven.tar.gz

RUN mkdir -p oc-cli maven && \
    tar -xvf openshift.tar.gz -C ./oc-cli --strip-components 1 && \
    tar -xvf maven.tar.gz -C ./maven --strip-components 1 && \
    chmod +x ./libs/transformxml

FROM openjdk:7-alpine
ENV MAVEN_HOME /usr/share/java/maven-3
ENV PATH $MAVEN_HOME/bin:$PATH
USER root

RUN apk update && \
    apk add --no-cache \
    git \
    docker \
    jq

COPY --from=base /usr/local/bin/jenkins-agent /usr/local/bin
COPY --from=base /home/maven /usr/share/java/maven-3
COPY --from=base /home/libs/transformxml /usr/local/bin
COPY --from=base /home/oc-cli/oc /usr/local/bin
COPY --from=base /home/maven_settings.xml /root/.m2/settings.xml
COPY --from=base /home/ca.crt /usr/local/share/ca-certificates/ca.crt
COPY --from=base /home/openshift-node-client-ca.crt /usr/local/share/ca-certificates/openshift-node-client-ca.crt
COPY --from=base /home/certs/aycapsu01ts471.cer aycapsu01ts471.cer
COPY --from=base /home/certs/aycapsu01ts472.cer aycapsu01ts472.cer

RUN update-ca-certificates && \
    ln -s /usr/local/bin/jenkins-agent /usr/local/bin/jenkins-slave

RUN  keytool \
    -import \
    -trustcacerts \
    -alias aycapsu01ts472.dso.aycap.bayad.co.th \
    -keystore $JAVA_HOME/jre/lib/security/cacerts \
    -file aycapsu01ts472.cer \
    -storepass changeit \
    -noprompt
RUN keytool \
    -import \
    -trustcacerts \
    -alias aycapsu01ts471.dso.aycap.bayad.co.th \
    -keystore $JAVA_HOME/jre/lib/security/cacerts \
    -file aycapsu01ts471.cer \
    -storepass changeit \
    -noprompt

VOLUME [ "/var/run/docker.sock" ]
ENTRYPOINT ["/usr/local/bin/jenkins-agent"]
