FROM jenkins/jnlp-slave:alpine

LABEL maintainer="joewalker"

USER root

ENV SDKMAN_DIR=/root/.sdkman
ENV SDKMAN_JAVA_VERSION=8.0.272-zulu

COPY ../assets .
COPY ../scripts/setup.sh .

RUN apk update && \
    apk add --no-cache \
    ca-certificates \
    zip \
    unzip \
    git \
    wget \
    curl \
    docker \
    openjdk7 \
    maven \
    jq

RUN chmod u+x *.sh && \
    bash ./setup.sh && \
    rm -f setup.sh

VOLUME [ "/var/run/docker.sock" ]